# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('page_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=250)),
                ('movie_logo', models.FileField(default=None, upload_to='')),
                ('trailer', models.CharField(default='', max_length=500)),
                ('about', models.CharField(default='', max_length=2000)),
                ('genre', models.CharField(default=None, max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('age_limit', models.IntegerField(default=0)),
                ('production', models.CharField(default=None, max_length=100)),
                ('is_announcement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_time', models.CharField(default=None, max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Movie')),
            ],
        ),
    ]
