# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='about',
        ),
        migrations.RemoveField(
            model_name='album',
            name='movie_trailer',
        ),
    ]
