# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170311_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='about',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='album',
            name='movie_trailer',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
