# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_movie_premier_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='premier_date',
            field=models.DateField(default=None),
        ),
    ]
