# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170311_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='trailer',
            field=models.CharField(default='', max_length=500),
        ),
    ]
